   const randomColor = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color', randomColor);
    const randomColor2 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color2', randomColor2);
    const randomColor3 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color3', randomColor3);
    const randomColor4 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color4', randomColor4);
    const randomColor5 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color5', randomColor5);
    const randomColor6 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color6', randomColor6);
    const randomColor7 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color7', randomColor7);
    const randomColor8 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color8', randomColor8);
    const randomColor9 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color9', randomColor9);
    const randomColor10 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color10', randomColor10);
    const randomColor11 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color11', randomColor11);
    const randomColor12 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color12', randomColor12);
    const randomColor13 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color13', randomColor13);
    const randomColor14 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color14', randomColor14);
    const randomColor15 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color15', randomColor15);
    const randomColor16 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color16', randomColor16);
    const randomColor17 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color17', randomColor17);
    const randomColor18 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color18', randomColor18);
    const randomColor19 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color19', randomColor19);
    const randomColor20 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color20', randomColor20);
    const randomColor21 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color21', randomColor21);
    const randomColor22 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color22', randomColor22);
    const randomColor23 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color23', randomColor23);
    const randomColor24 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color24', randomColor24);
    const randomColor25 = "#"+((1<<24)*Math.random()|0).toString(16);
    document.documentElement.style.setProperty('--main-bg-color25', randomColor25);
